---
abstract: 'Recursively compile a web service proxy'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Carp: '0'
  File::Spec: '0'
  HTTP::Response: '0'
  HTTP::Status: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Path::Tiny: '0'
  Scalar::Util: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0.94'
  Test::Most: '0'
  URI::file: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Compile-WSDL11-Recursive
requires:
  CHI: '0'
  HTTP::Exception: '0'
  LWP::UserAgent: '0'
  Modern::Perl: '0'
  Moo: '0'
  MooX::Types::MooseLike::Base: '0'
  URI: '0'
  XML::Compile::SOAP11: '0'
  XML::Compile::SOAP::Util: '0'
  XML::Compile::Transport::SOAPHTTP: '0'
  XML::Compile::Util: '0'
  XML::Compile::WSDL11: '0'
  XML::LibXML: '0'
  perl: '5.010'
  utf8: '0'
resources:
  bugtracker: https://github.com/mjgardner/xml-compile-wsdl11-recursive/issues
  homepage: https://github.com/mjgardner/xml-compile-wsdl11-recursive
  repository: git://github.com/mjgardner/xml-compile-wsdl11-recursive.git
version: '0.001'
